import type { ChapterMeta } from "./types";

// 42 chương = Phần 1-42, đúng mục lục sách Wyckoff Power Charting.
export const CHAPTERS_META: ChapterMeta[] = [
  { id: 1, title: "Chu Kỳ Thị Trường" },
  { id: 2, title: "Richard D. Wyckoff - Các Quy Tắc Thực Sự Của Trò Chơi" },
  { id: 3, title: "Hành Động Dừng Của Xu Hướng Giảm" },
  { id: 4, title: "Giai Đoạn Tích Lũy: Hấp Thụ Cổ Phiếu Như Một Miếng Bọt Biển" },
  { id: 5, title: "Hài Lòng Với Các Biểu Đồ Hiện Đại Theo Phong Cách Wyckoff" },
  { id: 6, title: "Francis Bacon - Tiết Lộ Bản Chất Xu Hướng Thị Trường" },
  { id: 7, title: "Nhảy Qua Con Lạch - Jumping the Creek" },
  { id: 8, title: "Wyckoff Accumulation" },
  { id: 9, title: "Wyckoff Uptrend" },
  { id: 10, title: "Đường Kênh Xu Hướng" },
  { id: 11, title: "Wyckoff Re-accumulation" },
  { id: 12, title: "Tổng Hợp Phân Tích Tái Tích Lũy" },
  { id: 13, title: "Khi Mối Xâm Nhập Vào Xu Hướng Tăng Giá" },
  { id: 14, title: "Lựa Chọn Ngã Rẽ - Tái Tích Lũy Hay Phân Phối" },
  { id: 15, title: "Theo Dõi Quả Bóng Cao Su Nảy" },
  { id: 16, title: "Chỉ Cần Đọc Và Phân Tích Biểu Đồ" },
  { id: 17, title: "Context is King" },
  { id: 18, title: "Wyckoff Distribution" },
  { id: 19, title: "Con Đường Đi Của Wyckoff" },
  { id: 20, title: "Dấu Hiệu Cảnh Báo Xu Hướng Hỗn Loạn" },
  { id: 21, title: "Câu Chuyện Đằng Sau Các Đường Xu Hướng" },
  { id: 22, title: "Wyckoff Re-distribution" },
  { id: 23, title: "Các Quy Luật Trong Phương Pháp Wyckoff" },
  { id: 24, title: "Composite Man/Operator - CO" },
  { id: 25, title: "Năm Bước Tiếp Cận Thị Trường" },
  { id: 26, title: "9 Bài Kiểm Tra Mua Bán" },
  { id: 27, title: "Hệ Thống Điểm Vào Lệnh POE Và Thoát Lệnh EXIT" },
  { id: 28, title: "Các Hành Động Và Test" },
  { id: 29, title: "Quy Luật Nhân Quả Trong Hành Động" },
  { id: 30, title: "Phá Vỡ Qua Tảng Băng - Break The Ice" },
  { id: 31, title: "Theo Dõi Dấu Chân Lớn Và Thiết Lập Chiến Dịch" },
  { id: 32, title: "Giới Thiệu Point And Figure (PnF)" },
  { id: 33, title: "Cách Sử Dụng Hiệu Quả PnF" },
  { id: 34, title: "Tại Sao PnF Hoạt Động Hiệu Quả" },
  { id: 35, title: "Phân Tích Sức Mạnh Tương Đối" },
  { id: 36, title: "Đánh Giá Sức Mạnh Qua Sóng" },
  { id: 37, title: "Phân Tích Ngành, Nhóm Ngành Cổ Phiếu" },
  { id: 38, title: "Thủ Thuật PnF" },
  { id: 39, title: "Nghiên Cứu Case Study" },
  { id: 40, title: "Xây Dựng Kỹ Năng" },
  { id: 41, title: "Trò Chơi Nội Tâm" },
  { id: 42, title: "Kết Hợp Tất Cả Lại" },
];
